import CodeBlock from "../CodeBlock"

const Contributing = () => {
    return (
        <section id='contributing' className="bg text-white pb-10">
            <h2>
                Contributing to react-confirm-manager
            </h2>
            <p>
                Thanks for your interest in contributing. This project is intentionally lightweight, so the contribution workflow is kept simple and explicit. Please read this fully before starting.
            </p>
            <h3 className="mb-4">
                Project Structure
            </h3>
            <pre className="text-white bg-gray-800 p-4 w-full overflow-auto">
                {`react-confirm-manager/
├─ src/               # Library source code
├─ dist/              # Built output (generated)
├─ example/           # Local playground app (Vite + React)
├─ CONTRIBUTING.md
├─ README.md
├─ package.json
├─ tsup.config.ts`}
            </pre>
            <div className="p-4">
                <ul className="list-disc">
                    <li>
                        src/ : where you make changes
                    </li>
                    <li>
                        dist/ : auto-generated by tsup (do not edit manually)
                    </li>
                    <li>
                        example/ : used to test changes locally
                    </li>
                </ul>
            </div>
            <h3 className="pt-4">
                Local Development Setup
            </h3>
            <h4>
                1. Clone the repository
            </h4>
            <CodeBlock language="bash" code="git clone https://github.com/SaadNasir-git/react-confirm-manager.git
cd react-confirm-manager" height="h-max" />
            <h4>
                2. Install dependencies (root)
            </h4>
            <CodeBlock language="bash" code="npm install" height="h-max" />
            <h3 className="mt-4">
                Development Workflow (IMPORTANT)
            </h3>
            <p>
                This project uses tsup watch mode for live rebuilding.
            </p>
            <h4 className="p-2">
                Terminal 1 : Run library in watch mode
            </h4>
            <p>
                From the project root:
            </p>
            <CodeBlock language="bash" code="npm run build:watch" height="h-max" />
            <div className="p-4">
                This will:
                <ul className="mt-4 list-disc">
                    <li>
                        Watch src/ for changes
                    </li>
                    <li>
                        Automatically rebuild dist/
                    </li>
                    <li>
                        Re-run post-build steps when files change
                    </li>
                </ul>
                <p>
                    Leave this terminal running.
                </p>
            </div>
            <h4>
                Terminal 2 : Run example app
            </h4>
            <CodeBlock language="bash" code="cd example
npm install
npm run dev" height="h-max" />
            <p>
                Open the provided local URL in your browser.
            </p>
            <h3 className="mb-4">
                How to Test Your Changes
            </h3>
            <div className="p-4">
                <ul className="list-disc">
                    <li>
                        Modify files inside src/
                    </li>
                    <li>
                        tsup automatically rebuilds the library
                    </li>
                    <li>
                        Refresh the browser running the example app
                    </li>
                    <li>
                        Verify behavior visually and via console logs
                    </li>
                </ul>
            </div>
        </section>
    )
}

export default Contributing